Fallout/Models/DesignTimeDbContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace Fallout.Models
{
  public class FalloutContextFactory : IDesignTimeDbContextFactory<FalloutContext>
  {

    FalloutContext IDesignTimeDbContextFactory<FalloutContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
          .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<FalloutContext>();

      builder.UseMySql(configuration["ConnectionStrings:DefaultConnection"], ServerVersion.AutoDetect(configuration["ConnectionStrings:DefaultConnection"]));

      return new FalloutContext(builder.Options);
    }
  }
}

Fallout/Models/FalloutContext.cs
using Microsoft.EntityFrameworkCore;

namespace Fallout.Models
{
  public class FalloutContext : DbContext
  {
    public DbSet<Shelter> Shelters { get; set; }
    public DbSet<Survivor> Survivors { get; set; }
    public DbSet<ShelterSurvivor> ShelterSurvivor { get; set; }

    public FalloutContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

Fallout/Models/Shelter.cs
using System.Collections.Generic;

namespace Fallout.Models
{
  public class Shelter
  {
    public Shelter()
    {
        this.JoinEntities = new HashSet<ShelterSurvivor>();
    }

    public int ShelterId { get; set; }
    public string Name { get; set; }
    public virtual ICollection<ShelterSurvivor> JoinEntities { get; set; }
  }
}

Fallout/Models/ShelterSuvivor.cs
namespace Fallout.Models
{
  public class ShelterSurvivor
  {       
    public int ShelterSurvivorId { get; set; }
    public int SurvivorId { get; set; }
    public int ShelterId { get; set; }
    public virtual Survivor Survivor { get; set; }
    public virtual Shelter Shelter { get; set; }
  }
}

Fallout/Models/Survivor.cs
using System.Collections.Generic;
using System;

namespace Fallout.Models
{
    public class Survivor
    {
        public Survivor()
        {
            this.JoinEntities = new HashSet<ShelterSurvivor>();
            this.Completed = false;
        }

        public int SurvivorId { get; set; }
        public string Description { get; set; }
        public bool Completed { get; set; }
        public DateTime Arrived {get;set;}

        public virtual ICollection<ShelterSurvivor> JoinEntities { get; set; }
    }
}

Fallout/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Fallout.Controllers
{
  public class HomeController : Controller
  {

    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }

  }
}

Fallout/Controllers/SheltersController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Fallout.Models;
using System.Collections.Generic;
using System.Linq;

namespace Fallout.Controllers
{
  public class SheltersController : Controller
  {
    private readonly FalloutContext _db;

    public SheltersController(FalloutContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Shelter> model = _db.Shelters.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Shelter category)
    {
      _db.Shelters.Add(category);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisShelter = _db.Shelters
        .Include(category => category.JoinEntities)
        .ThenInclude(join => join.Survivor)
        .FirstOrDefault(category => category.ShelterId == id);
      return View(thisShelter);
    }

    public ActionResult Edit(int id)
    {
      var thisShelter = _db.Shelters.FirstOrDefault(category => category.ShelterId == id);
      return View(thisShelter);
    }

    [HttpPost]
    public ActionResult Edit(Shelter category)
    {
      _db.Entry(category).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisShelter = _db.Shelters.FirstOrDefault(category => category.ShelterId == id);
      return View(thisShelter);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisShelter = _db.Shelters.FirstOrDefault(category => category.ShelterId == id);
      _db.Shelters.Remove(thisShelter);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Fallout/Controllers/SurvivorsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using Fallout.Models;

namespace Fallout.Controllers
{
  public class SurvivorsController : Controller
  {
    private readonly FalloutContext _db;

    public SurvivorsController(FalloutContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Survivors.OrderBy(survivor => survivor.Arrived).ToList());
    }

    public ActionResult Create()
    {
      ViewBag.ShelterId = new SelectList(_db.Shelters, "ShelterId", "Name");
      return View();
    }

    public ActionResult Details(int id)
    {
      var thisSurvivor = _db.Survivors
        .Include(survivor => survivor.JoinEntities)
        .ThenInclude(join => join.Shelter)
        .FirstOrDefault(survivor => survivor.SurvivorId == id);
      return View(thisSurvivor);
    }

    [HttpPost]
    public ActionResult Create(Survivor survivor, int ShelterId)
    {
      _db.Survivors.Add(survivor);
      _db.SaveChanges();
      if (ShelterId != 0)
      {
        _db.ShelterSurvivor.Add(new ShelterSurvivor() { ShelterId = ShelterId, SurvivorId = survivor.SurvivorId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Edit(int id)
    {
      var thisSurvivor = _db.Survivors.FirstOrDefault(survivor => survivor.SurvivorId == id);
      ViewBag.ShelterId = new SelectList(_db.Shelters, "ShelterId", "Name");
      return View(thisSurvivor);
    }

    [HttpPost]
    public ActionResult Edit(Survivor survivor, int ShelterId)
    {
      if (ShelterId != 0)
      {
        _db.ShelterSurvivor.Add(new ShelterSurvivor() { ShelterId = ShelterId, SurvivorId = survivor.SurvivorId });
      }
      _db.Entry(survivor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
        var thisSurvivor = _db.Survivors.FirstOrDefault(survivor => survivor.SurvivorId == id);
        return View(thisSurvivor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
        var thisSurvivor = _db.Survivors.FirstOrDefault(survivor => survivor.SurvivorId == id);
        _db.Survivors.Remove(thisSurvivor);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    public ActionResult AddShelter(int id)
    {
      var thisSurvivor = _db.Survivors.FirstOrDefault(survivor => survivor.SurvivorId == id);
      ViewBag.ShelterId = new SelectList(_db.Shelters, "ShelterId", "Name");
      return View(thisSurvivor);
    }

    [HttpPost]
    public ActionResult AddShelter(Survivor survivor, int ShelterId)
    {
      if (ShelterId != 0)
      {
        _db.ShelterSurvivor.Add(new ShelterSurvivor() { ShelterId = ShelterId, SurvivorId = survivor.SurvivorId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteShelter(int joinId)
    {
      var joinEntry = _db.ShelterSurvivor.FirstOrDefault(entry => entry.ShelterSurvivorId == joinId);
      _db.ShelterSurvivor.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Fallout/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Fallout Shelter List!</h1>
<p>@Html.ActionLink("See all shelters", "Index", "Shelters")</p>
<p>@Html.ActionLink("See all survivors", "Index", "Survivors")</p>

<img src="~/img/arm.png" class="float-right" alt="...">

Fallout/Views/Shared/Footer.cshtml
<div id="footer">Bottom div content</div>

Fallout/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Fallout Shelter List</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
    <link rel="stylesheet" href="~/css/fallout.css">
  </head>
  <body>
    <div class="screen">
    <div class="container">
      <div class="jumbotron">
    @RenderBody()
    @await Html.PartialAsync("Footer")
    </div>
    </div>
    </div>
  </body>
</html>

Fallout/Views/Shelters/Create.cshtml
@{
  Layout = "_Layout";
}

@model Fallout.Models.Shelter

<h4>Add a new shelter</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <input type="submit" value="Add new shelter" />
}
<p>@Html.ActionLink("Show all shelters", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Fallout/Views/Shelters/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Fallout.Models.Shelter

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Fallout/Views/Shelters/Details.cshtml
@{
  Layout = "_Layout";
}

@model Fallout.Models.Shelter

<h2>Shelter Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)<h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This category does not contain any survivors.</p>
}
else
{
  <h4>Survivors in this shelter:</h4>
  <ul>
    @foreach(var join in Model.JoinEntities)
    {
      <li>@join.Survivor.Description</li>
    }
  </ul>
}

<p>@Html.ActionLink("Back to Shelters", "Index")</p>
<p>@Html.ActionLink("Edit Shelter", "Edit", new { id = Model.ShelterId })</p>
<p>@Html.ActionLink("Delete Shelter", "Delete", new { id = Model.ShelterId })</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Fallout/Views/Shelters/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Fallout.Models.Shelter

<h2>Edit Record</h2>

<h4>Edit @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.ShelterId)

  @Html.LabelFor(model => model.Name) <span> &nbsp; </span>
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Fallout/Views/Shelters/Index.cshtml
@{
  Layout = "_Layout";
}

@using Fallout.Models;

<h1>Shelters</h1>

@if (@Model.Count == 0)
{
  <h3>No shelters have been added yet!</h3>
} 

<ul class="list-group">
  @foreach(Shelter shelter in Model)
  {
    <li class="list-group-item">@Html.ActionLink($"{shelter.Name}", "Details", new { id = shelter.ShelterId })</li>
  }
</ul>

<button>@Html.ActionLink("Add new shelter", "Create")</button>
<button>@Html.ActionLink("Home", "Index", "Home")</button>

Fallout/Views/Survivors/AddShelter.cshtml
@{
  Layout = "_Layout";
}

@model Fallout.Models.Survivor

<h2>Add a shelter</h2>

<h4>Add a shelter to this task: @Html.DisplayFor(model => model.Description)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.SurvivorId)

  @Html.Label("Select Shelter")
  @Html.DropDownList("ShelterId")

  <input type="submit" value="save"/>
}

<p>@Html.ActionLink("Back to List", "Index")</p>

Fallout/Views/Survivors/Create.cshtml
@{
  Layout = "_Layout";
}

@model Fallout.Models.Survivor

<h4>Add new survivor</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Description)
    @Html.TextBoxFor(model => model.Description)

    @Html.LabelFor(model => model.Arrived)
    @Html.TextBoxFor(model => model.Arrived, new {type = "date"})

    @Html.Label("Select Shelter")
    @Html.DropDownList("ShelterId")
    @* @Html.HiddenFor(model => model.Completed) *@
    <input type="submit" value="Add new survivor" class="btn btn-default"/>
}
<p>@Html.ActionLink("Show all survivors", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Fallout/Views/Survivors/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Fallout.Models.Survivor

<h2>Are you sure you want to delete this survivor?</h2>

@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Fallout/Views/Survivors/Details.cshtml
@{
  Layout = "_Layout";
}

@model Fallout.Models.Survivor

<h2>Survivor Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)</h3>
<p>Enrolled: @Model.Arrived.ToString("d")</p>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This survivor does not belong to any shelters.</p>
}
else
{
  <h4>Shelters this survivor belongs to:</h4>
    <ul>
    @foreach(var join in Model.JoinEntities)
    {
      <li class="list-group-item">@join.Shelter.Name</li>
      @using (Html.BeginForm("DeleteShelter", "Survivors"))
      {
        @Html.Hidden("joinId", @join.ShelterSurvivorId)
        <input type="submit" value="Delete"/>
      }
    }
    </ul>
}

<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Edit Survivor", "Edit", new { id = Model.SurvivorId })</p>
<p>@Html.ActionLink("Delete Survivor", "Delete", new { id = Model.SurvivorId })</p>
<p>@Html.ActionLink("Add a Shelter", "AddShelter", new { id = Model.SurvivorId })</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Fallout/Views/Survivors/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Fallout.Models.Survivor

<h2>Edit</h2>

<h4>Edit this task: @Html.DisplayFor(model => model.Description)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.SurvivorId)

  @Html.LabelFor(model => model.Description)
  @Html.EditorFor(model => model.Description)

  @Html.LabelFor(model => model.Arrived)
  @Html.EditorFor(model => model.Arrived)

  @Html.Label("Select Shelter")
  @Html.DropDownList("ShelterId")
  @Html.LabelFor(model => model.Completed)
  @Html.CheckBoxFor(model => model.Completed)
  <input type="submit" value="Save"/>
}

<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Fallout/Views/Survivors/Index.cshtml
@{
  Layout = "_Layout";
}

@using Fallout.Models;
@model List<Fallout.Models.Survivor>;

<h1>Survivors</h1>

@if (@Model.Count == 0)
{
  <h3>No survivors have been added yet!</h3>
}

<ul class="list-group">
@foreach (Survivor survivor in Model)
{
  <li class="list-group-item">
    @Html.ActionLink($"{survivor.Description}", "Details", new { id = survivor.SurvivorId })
    @if (survivor.Completed == true)
    {
      <span> - completed</span>;
    }
  </li>
}
</ul>

<button>@Html.ActionLink("Add new survivor", "Create")</button>
<button>@Html.ActionLink("Home", "Index", "Home")</button>